name: Build IndoDesk

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  APP_NAME: indodesk
  FLUTTER_VERSION: "3.24.5"
  LLVM_VERSION: "15.0.6"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VERSION: "1.4.6"

jobs:
  generate-bridge:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.75"
          components: rustfmt

      - name: Install flutter_rust_bridge_codegen
        run: cargo install flutter_rust_bridge_codegen --version 1.80.0 --locked

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Generate bridge
        run: |
          dart pub get
          ~/.cargo/bin/flutter_rust_bridge_codegen \
            --rust-input ../src/flutter_ffi.rs \
            --dart-output ./lib/generated_bridge.dart \
            --dart-decl-output ./lib/bridge_definitions.dart
        working-directory: flutter

      - name: Upload bridge artifact
        uses: actions/upload-artifact@v4
        with:
          name: bridge-artifact
          path: |
            ./flutter/lib/generated_bridge.dart
            ./flutter/lib/bridge_definitions.dart

  build-windows:
    needs: [generate-bridge]
    runs-on: windows-2022
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore bridge files
        uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "1.75"
          targets: x86_64-pc-windows-msvc
          components: "rustfmt"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Setup vcpkg with Github Actions binary cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
        shell: bash
        run: |
          if ! $VCPKG_ROOT/vcpkg \
            install \
            --triplet x64-windows-static \
            --x-install-root="$VCPKG_ROOT/installed"; then
            find "${VCPKG_ROOT}/" -name "*.log" | while read -r _1; do
              echo "$_1:"
              cat "$_1"
            done
            exit 1
          fi

      - name: Build rustdesk
        run: |
          python3 .\build.py --portable --hwcodec --flutter --vram --skip-portable-pack
          mv ./flutter/build/windows/x64/runner/Release ./indodesk

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: IndoDesk-Windows
          path: ./indodesk/

  build-macos:
    needs: [generate-bridge]
    runs-on: macos-14
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore bridge files
        uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./

      - name: Install build runtime
        run: |
          brew install llvm create-dmg nasm yasm cmake pkg-config

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "1.81"
          targets: aarch64-apple-darwin
          components: "rustfmt"

      - name: Setup vcpkg with Github Actions binary cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        run: |
          if ! $VCPKG_ROOT/vcpkg \
            install \
            --x-install-root="$VCPKG_ROOT/installed"; then
            find "${VCPKG_ROOT}/" -name "*.log" | while read -r _1; do
              echo "$_1:"
              cat "$_1"
            done
            exit 1
          fi

      - name: Build rustdesk
        run: |
          ./build.py --flutter --hwcodec --screencapturekit

      - name: Create DMG
        run: |
          create-dmg --icon "RustDesk.app" 200 190 \
            --hide-extension "RustDesk.app" \
            --window-size 800 400 \
            --app-drop-link 600 185 \
            indodesk-${{ env.VERSION }}-aarch64.dmg \
            ./flutter/build/macos/Build/Products/Release/RustDesk.app

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: IndoDesk-macOS
          path: indodesk-${{ env.VERSION }}-aarch64.dmg
